### ISSUE TITLE
The fmv cutscenes in Panzer Dragoon are freezing. Also no music on the first level

### ISSUE THREAD

**Issue by Krathoon** [srg320/Saturn_MiSTer#9]
### Version (or build number)

20230829

### Single or Dual SDRAM?

Single (128MB)

### Steps to reproduce

Play the game until you get a fmv cutscene right at the beginning. It will play a little bit and freeze.

You can hit start and skip it.

There is also no music on the very first level.

### Expected Behavior

I was expecting the fmv to fully play and music on the first level.

### Actual Behavior

The first fmv freezes and there is no music on the first level.

**Comment by Kuba-J** [comment]
I don't understand the reporting of bugs, if the author doesn't want it for now.

**Comment by KClough** [comment]
No one should be reporting bugs. 

Ideally, someone with admin access should [disable issues on github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/disabling-issues).

Personally, I'd rather `srg320`'s efforts go towards building this amazing core rather than having to deal with folks who choose to ignore his instructions.
